name: FluxWardrobe
version: ${version}
main: dev.rique.fluxwardrobe.FluxWardrobePlugin
api-version: '26.1.1'
author: Rique
description: High-performance wardrobe plugin for Paper and Folia.
folia-supported: true
softdepend:
  - PlaceholderAPI
  - Vault
  - CombatLogX

commands:
  wardrobe:
    description: Main FluxWardrobe command.
    aliases: [fw]
    usage: /wardrobe

permissions:
  fluxwardrobe.use:
    default: true
  fluxwardrobe.command.help:
    default: true
  fluxwardrobe.command.list:
    default: true
  fluxwardrobe.command.doctor:
    default: op
  fluxwardrobe.command.reload:
    default: op
  fluxwardrobe.command.migrate:
    default: op
  fluxwardrobe.admin:
    default: op
  fluxwardrobe.admin.*:
    default: op
    children:
      fluxwardrobe.admin: true
      fluxwardrobe.command.doctor: true
      fluxwardrobe.command.reload: true
      fluxwardrobe.command.migrate: true
  fluxwardrobe.command.*:
    default: op
    children:
      fluxwardrobe.command.help: true
      fluxwardrobe.command.list: true
      fluxwardrobe.command.doctor: true
      fluxwardrobe.command.reload: true
      fluxwardrobe.command.migrate: true
  fluxwardrobe.bypass.cooldown:
    default: op
  fluxwardrobe.bypass.restrictions:
    default: op
  fluxwardrobe.bypass.emptycheck:
    default: op
  fluxwardrobe.bypass.combat:
    default: op
  fluxwardrobe.notify.update:
    default: op
  fluxwardrobe.api.listen:
    default: false
