package dev.rique.fluxwardrobe.api.model;

public enum ResultCode {
    SUCCESS,
    SUCCESS_SAVED,
    SUCCESS_EQUIPPED,
    SUCCESS_DELETED,
    SUCCESS_RENAMED,
    DENIED_NO_PERMISSION,
    DENIED_SLOT_LOCKED,
    DENIED_EMPTY_ARMOR_REQUIRED,
    DENIED_COOLDOWN,
    DENIED_RESTRICTION_WORLD,
    DENIED_RESTRICTION_GAMEMODE,
    DENIED_RESTRICTION_COMBAT,
    DENIED_RESTRICTION_PLACEHOLDER,
    DENIED_NOTHING_SAVED,
    DENIED_INVALID_SLOT,
    DENIED_EVENT_CANCELLED,
    ERROR_PLAYER_OFFLINE,
    ERROR_STORAGE,
    ERROR_UNKNOWN
}
